### ISSUE TITLE
invalid change of license

### ISSUE THREAD

**Issue by martylamb** [ghajba/JSAP#1]
Hi Gábor,

I'm the original creator of JSAP.  It has been brought to my attention that your fork references the MIT license for JSAP, but I have released JSAP under the LGPL, which is not compatible with MIT.  I assume this is a simple mistake but must require you to change your LICENSE.txt accordingly.

I hope JSAP has been useful to you.

Best regards,

Marty

**Comment by ghajba** [comment]
Sorry, Marty, I missed this "little" part. Should be fixed by now.

Cheers,
Gabor

**Comment by martylamb** [comment]
Thanks for the quick response!  Much appreciated.

Cheers,
Marty
